### ISSUE TITLE
Renaming media files according to new schema

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#11]
See [here](https://github.com/MCT-master/mct-master.github.io/blob/master/README.md#embedding-images-videos-and-other-files) for instructions on how the new labeling schema applies to media assets on the repository and shared G-Drive. This issue is closely liked to #10.

Here is a brief:
```
Files stored in the G Drive ‘MCT Blog/asset’ should be placed in the appropriate sub-folder according to their type and named YYYY_MM_DD_username_filename.extension where:

    YYYY: year as per associate blog post
    MM: month as per associate blog post
    DD: day as per associate blog post
    username: your UiO username

Spaces or or special characters are not allowed in the file names.
```

**Comment by stefanofasciani** [comment]
All G Drive files has been renamed.
The remaining images under assets/images are being renamed (this will take a couple of more days). I will close the issue now.
Since it's me and Aleksander renaming the files and updating the associated blog posts, we will be using out usernames (it will take to long to back-trace who uploaded the file).
