### ISSUE TITLE
Mobile view word wrap issue

### ISSUE THREAD

**Issue by jacksongoode** [MCT-master/mct-master.github.io#14]
On some blog posts there are issues with wrapping long words (like url's). Here's an example...

[Example](https://imgur.com/70eibEM)

There is an extra horizontal space to the right of the blog as a result. Maybe there are some ways to hyphenate these cases within the blog post template?

**Comment by stefanofasciani** [comment]
I managed to replicate the same problem also on the desktop version entering a very long word.
[Example](https://imgur.com/a/zSgWJGk).
Same behavior happens with the post title.

This should not happen, words longer that the page width should continue on the next line (MS word does not include a hyphen in this case). I this is a bug of the "minima" template. I managed to fix it adding "overflow-wrap: break-word;" in  ".post-content" and in ".post-title" in /assets/main.scss (this file overrides default style settings of the template).

However, it is quite rare to have such long words, and lengthy URLs used in the href fiels (HTML) or in the () of markdown. i.e. they are not meant to be displayed on screen. Usually I do not recommend to include DOI links in the list of references (would be nice if Zoter can use the URL of the doi to generate a hyperlink rather than displaying it).

The chrome developer [tools](https://www.browserstack.com/guide/view-mobile-version-of-website-on-chrome) has been very handy to verify mobile layout on my local blog built (jekyll) before pushing them to the repository.
